<a href="https://colab.research.google.com/github/syedjafer/ML-Vault/blob/main/Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

def pooling(matrix, kernel, func):
    row, col = matrix.shape
    row_k, col_k = kernel
    f_matrix = matrix.flatten()
    leaving_range = list(range(col_k, col))
    stop_limit = (row-(row_k-1))*col
    resultant_array = []
    for itr in range(stop_limit):
        temp = []
        if (itr % col) + col_k -1 >= col:
            continue
        k = 0
        for ctr in range((row_k*col_k)+col_k*(len(leaving_range))):
            if k % col == 0:
                k = 0
            if k not in leaving_range:
                temp.append(f_matrix[itr+ctr])
            k+= 1
        resultant_array.append(func(temp))
    resultant_array = np.array(resultant_array)   
    resultant_array.resize((row-(row_k-1), col-(col_k-1)))
    return resultant_array

matrix = np.random.randint(low=10, high=51, size=(4,5))
kernel = (3,3)
max_res = pooling(matrix, kernel, np.max)
avg_res = pooling(matrix, kernel, np.average)

print(max_res)
print(avg_res)

[[50 50 50]
 [50 50 50]]
[[34.11111111 36.88888889 39.55555556]
 [32.11111111 33.11111111 35.55555556]]
